/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathRouteImport } from './routes/path'
import { Route as DevelopersUsernameRouteImport } from './routes/developers.$username'
import { Route as RepositoriesIdRouteImport } from './routes/repositories.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersUsernameRoute = DevelopersUsernameRouteImport.update({
  id: '/developers/$username',
  path: '/developers/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIdRoute = RepositoriesIdRouteImport.update({
  id: '/repositories/$id',
  path: '/repositories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/path': typeof PathRoute
  '/developers/$username': typeof DevelopersUsernameRoute
  '/repositories/$id': typeof RepositoriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/path': typeof PathRoute
  '/developers/$username': typeof DevelopersUsernameRoute
  '/repositories/$id': typeof RepositoriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/path': typeof PathRoute
  '/developers/$username': typeof DevelopersUsernameRoute
  '/repositories/$id': typeof RepositoriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/path' | '/developers/$username' | '/repositories/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/path' | '/developers/$username' | '/repositories/$id'
  id: '__root__' | '/' | '/path' | '/developers/$username' | '/repositories/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathRoute: typeof PathRoute
  DevelopersUsernameRoute: typeof DevelopersUsernameRoute
  RepositoriesIdRoute: typeof RepositoriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/$username': {
      id: '/developers/$username'
      path: '/developers/$username'
      fullPath: '/developers/$username'
      preLoaderRoute: typeof DevelopersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$id': {
      id: '/repositories/$id'
      path: '/repositories/$id'
      fullPath: '/repositories/$id'
      preLoaderRoute: typeof RepositoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathRoute: PathRoute,
  DevelopersUsernameRoute: DevelopersUsernameRoute,
  RepositoriesIdRoute: RepositoriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
